[package]
name = "bubblemath"
version = "0.1.0"
authors = ["Bubbler-4 <bubbler9903@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
itertools = "0.10.0"